#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap         	9

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Auto start
sxhkd &
~/.config/polybar/launch.sh &
xrandr --output HDMI-0 --mode 1920x1080 --rate 144.01 &
feh --bg-fill ~/.config/wallpapers/wall.jpg &
picom &
dunst &
python3 ~/.config/polybar/py/updatera_pris.py &


